### ISSUE TITLE
HARI LIBUR TIDAK SESUAI

### ISSUE THREAD

**Issue by yugiohduellink33** [guangrei/APIHariLibur_V2#1]
setelah pembaruan tanggal 29 Mei 2023
Di Bulan april tanggal 19 dan 20 tidak termasuk hari libur seharusnya masuk libur
dan tanggal 26 april termasuk hari libur seharusnya masuk hari kerja, minta tolong dicekkan minn
terimakasih
<img width="832" alt="image" src="https://github.com/guangrei/APIHariLibur_V2/assets/98403674/829a0d85-8656-478c-aa43-54f218a46b93">
sebelumnya saya cek di laman https://tanggalan.com/
makasihh minn

**Comment by guangrei** [comment]
> setelah pembaruan tanggal 29 Mei 2023 Di Bulan april tanggal 19 dan 20 tidak termasuk hari libur seharusnya masuk libur dan tanggal 26 april termasuk hari libur seharusnya masuk hari kerja, minta tolong dicekkan minn terimakasih <img alt="image" width="832" src="https://user-images.githubusercontent.com/98403674/241772226-829a0d85-8656-478c-aa43-54f218a46b93.png"> sebelumnya saya cek di laman https://tanggalan.com/ makasihh minn

ditanggalan itu datanya tidak update `Pemerintah merevisi masa cuti bersama Lebaran tahun 2023 ini dari semula 6 hari(21-26 April), menjadi 7 hari (19-25 April). ` https://www.cnbcindonesia.com/news/20230329133808-4-425485/sah-tanggal-libur-cuti-bersama-lebaran-2023-jadi-19-25-april

**Comment by guangrei** [comment]
> setelah pembaruan tanggal 29 Mei 2023 Di Bulan april tanggal 19 dan 20 tidak termasuk hari libur seharusnya masuk libur dan tanggal 26 april termasuk hari libur seharusnya masuk hari kerja, minta tolong dicekkan minn terimakasih <img alt="image" width="832" src="https://user-images.githubusercontent.com/98403674/241772226-829a0d85-8656-478c-aa43-54f218a46b93.png"> sebelumnya saya cek di laman https://tanggalan.com/ makasihh minn

[edit] oh itu kamu pakai json calendar yang lama (ada bugnya) di json calendar v2 libur kok https://raw.githubusercontent.com/guangrei/APIHariLibur_V2/main/calendar.json

**Comment by guangrei** [comment]
sekedar info yang versi lama juga sebenarnya up-to-date (lihat https://github.com/guangrei/Json-Indonesia-holidays/commit/da29ce46d80394ffa05fbca82a09854cf8511561) tapi beberapa jam lalu saya ganti/push dengan versi lokal yang belum update untuk memberitahukan bahwa yang lama deprecated, jadi harap tidak menggunakan json calendar versi lama 🙏

**Comment by yugiohduellink33** [comment]
nah cara updatenya gimana ya, apa cukup ganti link url di TanggalMerah.py line 12 ?
<img width="680" alt="image" src="https://github.com/guangrei/APIHariLibur_V2/assets/98403674/f58d7560-3dc9-4af2-8470-0c9d67df3c8a">
udah nyoba running tapi dibulan april hari nasional/libur ga masuk, contoh coding

`from pytanggalmerah import TanggalMerah
import datetime

# Create an instance of TanggalMerah
t = TanggalMerah(cache_path=None, cache_time=600)

# Specify the date range for April
start_date = "2023-04-01"
end_date = "2023-04-30"

# Iterate over the dates in the range
current_date = start_date
while current_date <= end_date:
    t.set_date(current_date[:4], current_date[5:7], current_date[8:])
    if not t.is_sunday() and not t.is_holiday():
        print(current_date)

    # Move to the next day
    current_date = (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(days=1)).strftime("%Y-%m-%d")` 

harap maklum min, sy non-IT baru terjun di git-hub juga

**Comment by guangrei** [comment]
> nah cara updatenya gimana ya, apa cukup ganti link url di TanggalMerah.py line 12 ? <img alt="image" width="680" src="https://user-images.githubusercontent.com/98403674/241786723-f58d7560-3dc9-4af2-8470-0c9d67df3c8a.png"> udah nyoba running tapi dibulan april hari nasional/libur ga masuk, contoh coding
> 
> `from pytanggalmerah import TanggalMerah import datetime
> 
> # Create an instance of TanggalMerah
> t = TanggalMerah(cache_path=None, cache_time=600)
> 
> # Specify the date range for April
> start_date = "2023-04-01" end_date = "2023-04-30"
> 
> # Iterate over the dates in the range
> current_date = start_date while current_date <= end_date: t.set_date(current_date[:4], current_date[5:7], current_date[8:]) if not t.is_sunday() and not t.is_holiday(): print(current_date)
> 
> ```
> # Move to the next day
> current_date = (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(days=1)).strftime("%Y-%m-%d")` 
> ```
> 
> harap maklum min, sy non-IT baru terjun di git-hub juga

tidak bisa asal ganti karena format jsonnya beda, berikut contoh penggunaan hari libur v2
```python
# -*-coding:utf8;-*-
import requests
from datetime import datetime

tahun = datetime.now().year
cek = f"{tahun}-12-25"
r = requests.get(
    "https://raw.githubusercontent.com/guangrei/APIHariLibur_V2/main/calendar.json").json()
if cek in r and r[cek]["holiday"]:
    print("summary:")
    print("\n".join(r[cek]['summary']))
else:
    print("tidak libur!")
```
untuk lib pytanggalmerahnya akan saya update secepatnya jika ada waktu 🙏

**Comment by guangrei** [comment]
@yugiohduellink33 sekarang library pytanggalmerah sudah terintegrasi dengan APIHariLibur_V2 silahkan lakukan upgrade 🙏

**Comment by yugiohduellink33** [comment]
> @yugiohduellink33 sekarang library pytanggalmerah sudah terintegrasi dengan APIHariLibur_V2 silahkan lakukan upgrade 🙏

wiih mantapp makasih banyak
