### ISSUE TITLE
How to Use in Golang ?

### ISSUE THREAD

**Issue by fikridzkr** [guangrei/APIHariLibur_V2#2]
How to Use this ?

**Comment by guangrei** [comment]
@fikridzkr check https://gist.github.com/guangrei/b71d5334774e58b7cbc5c3b81ca4d635

**Comment by fikridzkr** [comment]
> @fikridzkr check https://gist.github.com/guangrei/b71d5334774e58b7cbc5c3b81ca4d635

@guangrei When is this data update period?

**Comment by guangrei** [comment]
> > @fikridzkr check https://gist.github.com/guangrei/b71d5334774e58b7cbc5c3b81ca4d635
> 
> @guangrei When is this data update period?

It depends on Google Calendar, when Google update it holiday calendar, this repository will get updated automatically.

**Comment by fikridzkr** [comment]
> > > @fikridzkr check https://gist.github.com/guangrei/b71d5334774e58b7cbc5c3b81ca4d635
> > 
> > 
> > @guangrei When is this data update period?
> 
> It depends on Google Calendar, when Google update it holiday calendar, this repository will get updated automatically.

Ok, Thanks a lot !

**Comment by guangrei** [comment]
> > > > @fikridzkr check https://gist.github.com/guangrei/b71d5334774e58b7cbc5c3b81ca4d635
> > > 
> > > 
> > > @guangrei When is this data update period?
> > 
> > 
> > It depends on Google Calendar, when Google update it holiday calendar, this repository will get updated automatically.
> 
> Ok, Thanks a lot !

you are welcome

**Comment by guangrei** [comment]
@fikridzkr now you could use the go_holiday library https://github.com/cirebon-dev/go_holiday
